<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a014d768-d001-4dec-8a98-c7bb3d9090d7</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:ra\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':ra:') and equals(@name,'billing_address.last_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>f2cef04b-c479-43c4-aa99-6127a81718c8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:ra:</value>
        <webElementGuid>b259ae7b-b0d2-4ec7-a444-91dbf69f09bc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.last_name</value>
        <webElementGuid>22544217-e5cc-4af6-a96f-d5f18a40b393</webElementGuid>
    </webElementProperties>
</WebElementEntity>