<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a87a3df4-e853-436b-b9e7-0d2e6a77038c</elementGuidId>
    <imagePath></imagePath>
    <name>input_receive_marketing_info</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-contact-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'receive_marketing_info') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>48354b2f-8009-4d4e-87fc-021a81af81f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>receive_marketing_info</value>
        <webElementGuid>d1f1754e-ead5-4ef4-9e39-1b23e7831ed3</webElementGuid>
    </webElementProperties>
</WebElementEntity>