<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ba7774a-c4c3-4443-905e-04771f686745</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_zip</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[4]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-shipping-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rd:') and equals(@name,'billing_address.zip') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>989e408a-a514-4a72-8b8b-60e3c3be7bb7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rd:</value>
        <webElementGuid>53e1cac8-757e-49e0-8ec2-ba140d93d84a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.zip</value>
        <webElementGuid>5de7a851-81a0-4c03-9924-c08458206547</webElementGuid>
    </webElementProperties>
</WebElementEntity>