<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4c7fc4f7-9ea9-4d9b-bc52-cf6bcccec5f6</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_first_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:ra\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':ra:') and equals(@name,'billing_address.first_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>02baea02-267d-4d37-9e2f-f82aeb84a6cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:ra:</value>
        <webElementGuid>c0ce605e-21a3-4a97-9986-211edf71cb95</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.first_name</value>
        <webElementGuid>73ba0387-41a3-4eea-a59f-d86c833690aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>