<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f24a7078-707f-4caa-ad34-6c211093b048</elementGuidId>
    <imagePath></imagePath>
    <name>input_shipping_address_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r3\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r3:') and equals(@name,'shipping_address.last_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>f50cdc87-8d3e-4550-9af3-d1de5d742918</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r3:</value>
        <webElementGuid>ac17ea38-583a-4a95-a8ba-1fe1b8cb5174</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.last_name</value>
        <webElementGuid>d7676081-c3bb-4a0e-b30c-c8edadb1a6d0</webElementGuid>
    </webElementProperties>
</WebElementEntity>