<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f40351ce-a377-4453-b936-bb62de31bddd</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_the_same</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[3]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-indeterminate]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'billing_address_the_same') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>a3491efc-2676-49ec-81ef-bfbbe18d65c1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address_the_same</value>
        <webElementGuid>f5456253-b0e8-488d-bd37-f5b214753121</webElementGuid>
    </webElementProperties>
</WebElementEntity>