<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4bae18b3-f3e5-43b6-bfd2-ac11b4d60ec2</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:rb\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rb:') and equals(@name,'billing_address.last_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>201a05f7-d73c-43fe-9e47-5861ec40a5a3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rb:</value>
        <webElementGuid>ad4c81ea-808a-465a-a29e-a35244d5475d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.last_name</value>
        <webElementGuid>69337d04-dd9c-461b-8f27-b987b2055fa9</webElementGuid>
    </webElementProperties>
</WebElementEntity>