<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dfd4b6b9-4541-4f83-b259-c6f2d50f91cd</elementGuidId>
    <imagePath></imagePath>
    <name>input_shipping_address_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-shipping-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r3:') and equals(@name,'shipping_address.last_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>7b4e8bea-6132-4544-b6ea-25f1210fc2b8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r3:</value>
        <webElementGuid>260cd0e1-fb5e-4a61-a560-33128f30a874</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.last_name</value>
        <webElementGuid>624edf94-ab8d-432c-a74f-47a7a5819dc1</webElementGuid>
    </webElementProperties>
</WebElementEntity>