<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de139e24-d447-49f1-afae-3136e444b46e</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'bdl-checkout bdl-checkout_show')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>bdl-checkout bdl-checkout_show</value>
        <webElementGuid>0ff09e1c-894f-4937-9dd8-b4295d6dd919</webElementGuid>
    </webElementProperties>
</WebElementEntity>